### ISSUE TITLE
playground is not working

### ISSUE THREAD

**Issue by VladislavYak** [lukasmasuch/streamlit-pydantic#56]
<img width="747" alt="image" src="https://github.com/LukasMasuch/streamlit-pydantic/assets/69644103/5e48aa81-5441-479d-8ea7-c4291b2eb7ba">

https://lukasmasuch-streamlit-pydantic-playgroundplayground-app-711bhu.streamlit.app/

**Comment by lukasmasuch** [comment]
Fixed :) the playground is working again: https://st-pydantic.streamlit.app/
