### ISSUE TITLE
I would like to help maintain this project

### ISSUE THREAD

**Issue by MatanRubin** [LukasMasuch/streamlit-pydantic#59]
Hi,
It seems like this valuable project is no longer maintained. I would like to help maintain it.
I thought about forking it, but I think it would be better to use the existing project because this is what people are currently using.

@LukasMasuch , would you like to cooperate on this?

**Comment by MatanRubin** [comment]
@gaby , I’ve forked the repo, merged all open PRs, and released a new version with the name st-pydantic. I intend on adding more features and some testing soon. Feel free to give st-pydantic a try, and please share any feedback you have.

**Comment by KirmTwinty** [comment]
Great thank you!

**Comment by LukasMasuch** [comment]
Sorry for the long silence on this and mostly abandoning the project for a long time :( 

@MatanRubin [st-pydantic](https://github.com/MatanRubin/st-pydantic) looks great! I also invited you - and @HIL340
 - to `streamlit-pydantic` today and will give you write access. I think I need to look into the CI part to make it possible again to update it on pypi.

**Comment by MatanRubin** [comment]
Thanks @LukasMasuch! If you can get the CI to work again I can shift my work to this repo and drop the fork.

**Comment by LukasMasuch** [comment]
@MatanRubin Migrated everything to [rye](https://github.com/astral-sh/rye), CI should be working again :)

**Comment by MatanRubin** [comment]
Woohoo! Thanks @LukasMasuch !

**Comment by lukasmasuch** [comment]
@MatanRubin @HIL340 release pipeline is also fixed and working :) And the playground app is fixed! I'm planning to do a release soon to get the pydantic 2.0 support out.
