### ISSUE TITLE
BaseSettings is not on pydantic-settings

### ISSUE THREAD

**Issue by yechielb2000** [lukasmasuch/streamlit-pydantic#60]
current version 0.6.0

**Describe the bug:**

Could not use the library because an import error in the library

**Expected behaviour:**

working library...

**Steps to reproduce the issue:**

pip install streamlit_pydantic XD
-->

**Technical details:**

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.8/migration/#basesettings-has-moved-to-pydantic-settings for more details. For further information visit https://errors.pydantic.dev/2.8/u/import-error

**Possible Fix:**

import [here](https://github.com/LukasMasuch/streamlit-pydantic/blob/390a45aba7bf8caccc297c335715cc141db490af/src/streamlit_pydantic/settings.py#L4) from pydantic-settings instead of pydantic

**Note**
I see that you fixed it but somehow installing still gives the old vesrion of the code, even tho i have installed latest version

**Comment by felipeboffnunes** [comment]
Not a true fix but you can mainly set pydantic to be 1.9 on your requirements and it will work.
Example on Pipenv:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
streamlit = "==1.37.1"
streamlit-pydantic = "==0.6.0"
pydantic = "==1.9"

[dev-packages]

[requires]
python_version = "3.12"
python_full_version = "3.12.1"
```

**Comment by lukasmasuch** [comment]
Support for pydantic settings from 2.0 has been fixed in the latest `main` branch and will be released soon.

**Comment by mrtj** [comment]
Hello, can we have an ETA about the release? This bug is currently breaking the library.
